### ISSUE TITLE
[Prism] Blueprint calculator throws an exception on open

### ISSUE THREAD

**Issue by Eshva** [EveHQ-Team/EveHQ#13]
##Steps to reproduce##
1. Open BP Manager.
2. Double click on any blueprint.

##Present##
Exception window open.

##Expected##
Blueprint calculator window open with no exceptions.

##Possible reason and solution##
EveHQ.Esi.dll isn't present in application folder. It isn't present in installer script. Should add it to the list of EveHQ files in the installation scripts (both Release and Debug)

```
*****START Exception Details*****
Message: Could not load file or assembly 'EveHQ.Esi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Не удается найти указанный файл.
Source: EveHQ.Prism
StackTrace:    at EveHQ.Prism.Forms.FrmBPCalculator.DisplayProductionInformation()
   at EveHQ.Prism.Forms.FrmBPCalculator.UpdateBlueprintInformation() in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Forms\frmBPCalculator.vb:line 912
   at EveHQ.Prism.Forms.FrmBPCalculator.ProductionResourcesChanged() in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Forms\frmBPCalculator.vb:line 901
   at EveHQ.Prism.Controls.PrismResources.set_ProductionJob(Job value) in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Controls\PrismResources.vb:line 86
   at EveHQ.Prism.Forms.FrmBPCalculator.CalculateProductionResources() in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Forms\frmBPCalculator.vb:line 1010
   at EveHQ.Prism.Forms.FrmBPCalculator.cboBPs_SelectedIndexChanged(Object sender, EventArgs e) in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Forms\frmBPCalculator.vb:line 780
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at DevComponents.DotNetBar.Controls.ComboBoxEx.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ComboBox.set_SelectedItem(Object value)
   at EveHQ.Prism.Forms.FrmBPCalculator.frmBPCalculator_Load(Object sender, EventArgs e) in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Forms\frmBPCalculator.vb:line 398
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevComponents.DotNetBar.RibbonForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevComponents.DotNetBar.RibbonForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
*****END Exception Details*****


========== Plug-ins ==========

EveHQ.HQF.dll (1.0.0.0)
EveHQ.KillMailViewer.dll (1.0.0.0)
EveHQ.Prism.dll (1.0.0.0)
EveHQ.Void.dll (1.0.0.0)


========= System Info =========

Operating System: Microsoft Windows NT 6.2.9200.0
.Net Framework Version: 4.0.30319.42000
EveHQ Location: A:\Program Files\Games\EveHQ
EveHQ Cache Locations: C:\Users\mike\AppData\Roaming\EveHQ
```

**Comment by Eshva** [comment]
Fixed. Will be released in version 2.31.2.0
