### ISSUE TITLE
[Prism] Updating BPs for Assets 

### ISSUE THREAD

**Issue by travhull** [EveHQ-Team/EveHQ#96]
*EveHQ Error Report*

EveHQ Version: 2.31.8.0
Date: 11/10/2017 07:46:35
Error: The given key was not present in the dictionary.
----
\\{panel:title=StackTrace|borderStyle=dashed|bordercolor=#ccc|titleBGColor=#eee|bgColor=#eee}*****START Exception Details*****
Message: The given key was not present in the dictionary.
Source: System
StackTrace:    at System.Collections.Generic.SortedList`2.get_Item(TKey key)
   at EveHQ.Prism.Forms.FrmPrism.btnUpdateBPsFromAssets_Click(Object sender, EventArgs e) in B:\Projects\GitHub\EveHQ-Team\EveHQ\EveHQ.Prism\Forms\frmPrism.vb:line 4171
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
*****END Exception Details*****

========== Plug-ins ==========

EveHQ.HQF.dll (1.0.0.0)
EveHQ.KillMailViewer.dll (1.0.0.0)
EveHQ.Prism.dll (1.0.0.0)
EveHQ.Void.dll (1.0.0.0)

========= System Info =========

Operating System: Microsoft Windows NT 6.2.9200.0
.Net Framework Version: 4.0.30319.42000
EveHQ Location: C:\Program Files (x86)\EveHQ
EveHQ Cache Locations: C:\Users\Travis\AppData\Roaming\EveHQ
\\{panel}

**Comment by Eshva** [comment]
Cannot reproduce 2.31.10
